name: Sixth action of this repo

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Uploading files to dist directory
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist/app.txt

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Coping files from dist directory
        uses: actions/download-artifact@v5
        with:
          name: app

      - shell: bash
        run: |
          value=`cat dist/app.txt`
          echo The result is $value
