name: Fith action in the repo

on: 
  push:
    branches:
      - main
    

env:
  APP_GLOBAL: teste
  
jobs: 
  secrets_variables:
    runs-on: ubuntu-latest
    steps:
      - run: echo $API_TOKEN
      - run: echo $APP_GLOBAL
      - run: echo {{ $ENVIRONMENT_NAME }}
