name: Sixth action of this repo

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "testando" >> teste.txt
      - name: Uploading files to dist directory
        uses: actions/upload-artifact@v4
        with:
          name: teste
          path: teste.txt

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Coping files from dist directory
        uses: actions/download-artifact@v5
        with:
          name: teste

      - shell: bash
        run: |
          value=`cat teste.txt`
          echo The result is $value
