name: Forth action in this repo

on:
  push:
    branches:
      - main


jobs:
  matriz:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [24, 26]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          