name: Production

on: 
  pull_request:

jobs:
  produtction:
    runs-on: ubuntu-latest
    environment: produtction
    steps:
      - run: echo "Deploy!"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref}}
  cancel-in-progress: true